---
# Source: zookeeper-operator/templates/rbac.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zk-0-zookeeper-operator
  namespace: "app-zk"
  labels:
    app: "zk-0-zookeeper-operator"
    chart: "zookeeper-operator-0.0.2"
    release: "zk-0"
    heritage: "Helm"
---
# Source: zookeeper-operator/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.pravega.io
  labels:
    app: "zk-0-zookeeper-operator"
    chart: "zookeeper-operator-0.0.2"
    release: "zk-0"
    heritage: "Helm"
spec:
  group: zookeeper.pravega.io
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeperclusters
    singular: zookeepercluster
    shortNames:
      - zk
  additionalPrinterColumns:
  - name: Members
    type: integer
    description: The number zookeeper members running
    JSONPath: .status.replicas
  - name: Ready Members
    type: integer
    description: The number zookeeper members ready
    JSONPath: .status.readyReplicas
  - name: Internal Endpoint
    type: string
    description: Client endpoint internal to cluster network
    JSONPath: .status.internalClientEndpoint
  - name: External Endpoint
    type: string
    description: Client endpoint external to cluster network via LoadBalancer
    JSONPath: .status.externalClientEndpoint
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}
---
# Source: zookeeper-operator/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zk-0-zookeeper-operator
  labels:
    app: "zk-0-zookeeper-operator"
    chart: "zookeeper-operator-0.0.2"
    release: "zk-0"
    heritage: "Helm"
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
---
# Source: zookeeper-operator/templates/rbac.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: zk-0-zookeeper-operator
  labels:
    app: "zk-0-zookeeper-operator"
    chart: "zookeeper-operator-0.0.2"
    release: "zk-0"
    heritage: "Helm"
subjects:
- kind: ServiceAccount
  name: zk-0-zookeeper-operator
  namespace: app-zk
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zk-0-zookeeper-operator
---
# Source: zookeeper-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-0-zookeeper-operator
  namespace: "app-zk"
  labels:
    app: "zk-0-zookeeper-operator"
    chart: "zookeeper-operator-0.0.2"
    release: "zk-0"
    heritage: "Helm"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zk-0-zookeeper-operator
      release: zk-0
  template:
    metadata:
      labels:
        app: "zk-0-zookeeper-operator"
        chart: "zookeeper-operator-0.0.2"
        release: "zk-0"
        heritage: "Helm"
    spec:
      serviceAccountName: zk-0-zookeeper-operator
      containers:
      - name: zookeeper-operator
        image: "pravega/zookeeper-operator:0.2.2"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 60000
          name: metrics
        env:
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: OPERATOR_NAME
          value: zk-0-zookeeper-operator
        resources:
            {}
