---
# Source: zookeeper-operator/templates/service_account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zookeeper-operator
  namespace: app-zk
---
# Source: zookeeper-operator/templates/crd.yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: zookeeperclusters.zookeeper.pravega.io
spec:
  group: zookeeper.pravega.io
  names:
    kind: ZookeeperCluster
    listKind: ZookeeperClusterList
    plural: zookeeperclusters
    singular: zookeepercluster
    shortNames:
      - zk
  additionalPrinterColumns:
    - name: Replicas
      type: integer
      description: The number of ZooKeeper servers in the ensemble
      JSONPath: .spec.replicas
    - name: Ready Replicas
      type: integer
      description: The number of ZooKeeper servers in the ensemble that are in a Ready state
      JSONPath: .status.readyReplicas
    - name: Internal Endpoint
      type: string
      description: Client endpoint internal to cluster network
      JSONPath: .status.internalClientEndpoint
    - name: External Endpoint
      type: string
      description: Client endpoint external to cluster network via LoadBalancer
      JSONPath: .status.externalClientEndpoint
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
  scope: Namespaced
  version: v1beta1
  subresources:
    status: {}
---
# Source: zookeeper-operator/templates/clusterrole.yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zk-0-zookeeper-operator
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
---
# Source: zookeeper-operator/templates/clusterrolebinding.yaml
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zk-0-zookeeper-operator
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: app-zk
roleRef:
  kind: ClusterRole
  name: zk-0-zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: zookeeper-operator/templates/role.yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zk-0-zookeeper-operator
  namespace: app-zk
rules:
- apiGroups:
  - zookeeper.pravega.io
  resources:
  - "*"
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
---
# Source: zookeeper-operator/templates/rolebinding.yaml
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: zk-0-zookeeper-operator
  namespace: app-zk
subjects:
- kind: ServiceAccount
  name: zookeeper-operator
  namespace: app-zk
roleRef:
  kind: Role
  name: zk-0-zookeeper-operator
  apiGroup: rbac.authorization.k8s.io
---
# Source: zookeeper-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zk-0-zookeeper-operator
  namespace: app-zk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: zk-0-zookeeper-operator
  template:
    metadata:
      labels:
        name: zk-0-zookeeper-operator
        component: zookeeper-operator
    spec:
      serviceAccountName: zookeeper-operator
      containers:
        - name: zk-0-zookeeper-operator
          image: "pravega/zookeeper-operator:0.2.2"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6000
              name: metrics
          command:
            - zookeeper-operator
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: zk-0-zookeeper-operator
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi
